### ISSUE TITLE
Set Preheater duration - working - no issue

### ISSUE THREAD

**Issue by msandvold** [skodaconnect/homeassistant-skodaconnect#188]
I've had some problems getting the "Pre heater duration" to work.

**First step i OK**:

In configuration.yaml:

input_number:
  pheater_duration:
    name: "Pre-heater duration"
    initial: 20
    min: 10
    max: 60
    step: 10
    unit_of_measurement: min

Create the automation, in yaml or via GUI editor. You can find the device id by going to Settings->Devices & Services and then clicking on the device for the Skodaconnect vehicle. The device ID will show in the web browser address bar after "/config/devices/device/". The ID can also be found by using the GUI services editor under developer tools. Choose one of the skodaconnect services and choose your vehicle. Change to YAML mode and copy the device ID.

**this is my automation in yaml**

It was the duration - state from input_number.pheater_duration that resulted in a number with one decimal -> 10.0 / 20.0 / 30.0. So I had to edit the duration to get the expxted state correct.

New automation -> change to yaml mode ->**paste code** -> replace "Your Device ID for vehicle" with Your ID, as described above.

```
alias: Pre-heater duration
description: ""
trigger:
  - platform: state
    entity_id: input_number.pheater_duration
condition: []
action:
  - service: skodaconnect.set_pheater_duration
    data_template:**
      device_id: <Your Device ID for vehicle>
      duration: "{{ (states('input_number.pheater_duration') | float ) | round(0) }}"
mode: single
```

**You need to set duration before BEFORE starting the heater/ventilation.**
