### ISSUE TITLE
Change the color of entity icon - like battery level

### ISSUE THREAD

**Issue by maijo366** [skodaconnect/homeassistant-skodaconnect#226]
Hello,
how can i automate or let the color change of an custom entity - like the battery level.
Custom Sensor: Battery Level aktuell - kWh
![grafik](https://github.com/skodaconnect/homeassistant-skodaconnect/assets/96180786/a8722d31-3a68-433c-8373-ea20e4286792)

**Comment by dvx76** [comment]
You need to use a card which supports customizing the icon color with a template. Personally I use [mushroom cards](https://github.com/piitaya/lovelace-mushroom).

E.g.

```yaml
type: custom:mushroom-template-card
entity: sensor.skodavin_battery_level
icon: '{{ state_attr("sensor.skodavin_battery_level", "icon") }}'
icon_color: {% if states("sensor.skodavin_battery_level") | int > 50 %}green{% elif states("sensor.skodavin_battery_level") | int > 20 %}orange{% else %}red{% endif %}
primary: '{{ states("sensor.tmbjc9ny8nf057114_battery_level") }} %'
layout: vertical
```
