### ISSUE TITLE
Calling "skodaconnect.set_charge_limit" returns "Could not find associated coordinator for given vehicle"

### ISSUE THREAD

**Issue by bkleif** [skodaconnect/homeassistant-skodaconnect#246]
**Describe the bug**
When calling the service "skodaconnect.set_charge_limit", it fails with "Could not find associated coordinator for given vehicle
".

I am just trying to call the service directly from developer tools. I have a Skoda Enyaq, and have also tried with other limits, such at 50.

service: skodaconnect.set_charge_limit
data:
  device_id: 36xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxeae
  limit: 100

**Is this working in MySkoda app?***
Yes- but the app is so crap and unstable, it would be nice to do it from HA.

**Latest working release**
I have not tried to call the service in previous releases. I am currently using 1.2.8

**Debug logs**

Traceback (most recent call last):
  File "/config/custom_components/skodaconnect/__init__.py", line 280, in get_car
    dev_coordinator = hass.data[DOMAIN][conf_entry]['data'].coordinator
                      ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: '23cba6bd0c353ca6262129f26f927648'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 704, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 666, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2067, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2104, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/skodaconnect/__init__.py", line 376, in set_charge_limit
    car = await get_car(service_call)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/skodaconnect/__init__.py", line 282, in get_car
    raise SkodaConfigException('Could not find associated coordinator for given vehicle')
skodaconnect.exceptions.SkodaConfigException: Could not find associated coordinator for given vehicle


**Installation:**
 - Hass OS 11.2, Core 2023.12.2

**Additional context**
The entities are working great, showing battery level, enabling climatisation and so on.

**Comment by bkleif** [comment]
Fixed the issue by deleting the helpers I had created which used sensors from the skodaconnect integration.

**Comment by georgbachmann** [comment]
I had the same issue. I added a template number entity (see following code) to be able to set it inside the UI and when I removed it, it worked calling the service from the developer tools.
```
template:
  - number:
      - name: enyaq_charge_limitation
        unique_id: "enyaq_charge_limitation"
        state: "{{ states('sensor.skoda_enyaq_minimum_charge_level') | int(0) }}"
        set_value:
          - service: skodaconnect.set_charge_limit
            data:
              limit: "{{ value | int(0) }}"
              device_id: <my-id>
        step: "10"
        min: "10"
        max: "100"
```


But the problem is that it only once. I did set it to 90 -> Send -> OK. Then changed it to 80 -> Send -> Error
Or at least once per 20 seconds or so then it did work again once. In the logs I found this:

```
websocket_api script: Error executing script. Unexpected error for call_service at pos 1: Charging action already in progress
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 476, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 713, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 675, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2149, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2186, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/skodaconnect/__init__.py", line 380, in set_charge_limit
    state = await car.set_charge_limit(limit)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/skodaconnect/vehicle.py", line 534, in set_charge_limit
    return await self.set_charger(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/skodaconnect/vehicle.py", line 443, in set_charger
    raise SkodaRequestInProgressException('Charging action already in progress')
skodaconnect.exceptions.SkodaRequestInProgressException: Charging action already in progress
```
Seems that the API requests are taking that long? Or Skoda/VW has some limitations on how often they might get called?

This might also explain why the Skoda App is that crappy :D

Would be great to know how I can still have my number-template-entity so that I can have a slider of stepper or something similar.

**Comment by Farfar** [comment]
> I had the same issue. I added a template number entity (see following code) to be able to set it inside the UI and when I removed it, it worked calling the service from the developer tools.
> 
> ```
> template:
>   - number:
>       - name: enyaq_charge_limitation
>         unique_id: "enyaq_charge_limitation"
>         state: "{{ states('sensor.skoda_enyaq_minimum_charge_level') | int(0) }}"
>         set_value:
>           - service: skodaconnect.set_charge_limit
>             data:
>               limit: "{{ value | int(0) }}"
>               device_id: <my-id>
>         step: "10"
>         min: "10"
>         max: "100"
> ```
> 
> But the problem is that it only once. I did set it to 90 -> Send -> OK. Then changed it to 80 -> Send -> Error Or at least once per 20 seconds or so then it did work again once. In the logs I found this:
> 
> ```
> websocket_api script: Error executing script. Unexpected error for call_service at pos 1: Charging action already in progress
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 476, in _async_step
>     await getattr(self, handler)()
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 713, in _async_call_service_step
>     response_data = await self._async_run_long_action(
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 675, in _async_run_long_action
>     return long_task.result()
>            ^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/core.py", line 2149, in async_call
>     response_data = await coro
>                     ^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/core.py", line 2186, in _execute_service
>     return await target(service_call)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/skodaconnect/__init__.py", line 380, in set_charge_limit
>     state = await car.set_charge_limit(limit)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/skodaconnect/vehicle.py", line 534, in set_charge_limit
>     return await self.set_charger(data)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/skodaconnect/vehicle.py", line 443, in set_charger
>     raise SkodaRequestInProgressException('Charging action already in progress')
> skodaconnect.exceptions.SkodaRequestInProgressException: Charging action already in progress
> ```
> 
> Seems that the API requests are taking that long? Or Skoda/VW has some limitations on how often they might get called?
> 
> This might also explain why the Skoda App is that crappy :D
> 
> Would be great to know how I can still have my number-template-entity so that I can have a slider of stepper or something similar.

Some actions for older cars take a long time to complete, up to 3-5 minutes sometimes before some kind of timeout is reached in the backend if the vehicle doesn't respond.
But it's also possible that the integration got hung up thinking there's a request still being processed. In that case a reload of the integration should help.

**Comment by dvx76** [comment]
You can use the `sensor.skoda_enyaq_request_results` to determine if there's any ongoing request (which will cause any additional request to fail with `Charging action already in progress`).

I've wrapped the actions I use often in scripts which use that sensor to block until there's no more request in progress.

E.g.

```yaml
alias: Skoda - Turn off Charging and Wait
sequence:
  - if:
      - condition: state
        entity_id: switch.tmbj......_charging
        state: "on"
    then:
      - type: turn_off
        device_id: e9d855c76d63e49117ae0d255699c12f
        entity_id: switch.tmbj......_charging
        domain: switch
      - delay:
          hours: 0
          minutes: 1
          seconds: 0
          milliseconds: 0
      - wait_template: "{{ is_state('sensor.skoda_enyaq_request_results', 'Success') }}"
        continue_on_timeout: true
        timeout: "300"
mode: single
icon: mdi:battery-clock-outline
```
