### ISSUE TITLE
Time Format for departure schedule

### ISSUE THREAD

**Issue by Cully81** [skodaconnect/homeassistant-skodaconnect#302]
Hello,

I would like to set the schedule for preheating my new Kodiaq using automation. Unfortunately, this does not work yet. I have created the following command:

`action: skodaconnect.set_departure_schedule
data:
  enabled: true  
  recurring: true
  device_id: 123456789
  id: 3
  time: "08:15"
  temp: 21.5
  days: yyyyyyy
  climatisation: true
`

What makes me wonder is the time format.
If I enter the time as 08:15 in the GUI, I cannot run the automation. I get an error “Unknown error”. Only when I put the time in quotation marks in the GUI can I execute the script. The code then says 

`  time: "\"08:15\""`

However, the schedule is still not activated in my car.
Are time settings correct and what could be the problem in my code?

Many thanks and best regards
Dennis

**Comment by WebSpider** [comment]
Departure schedules are not supported yet in `homeassistant-myskoda`, but they are in skodaconnect/homeassistant-skodaconnect
We'll consider this a feature request :-)

**Comment by Cully81** [comment]
Can no one say anything about this?
Is there anyone who has this working and could post their YAML here?

**Comment by WebSpider** [comment]
You can find examples here:

https://github.com/skodaconnect/homeassistant-skodaconnect/blob/main/custom_components%2Fskodaconnect%2Fservices.yaml#L123

**Comment by Cully81** [comment]
Thanks for the hint.
I have tried to implement this, but simply get “Unknown Error” when executing.
Where is my error?

````
action: skodaconnect.set_departure_schedule
data:
  enabled: true
  recurring: false
  device_id: 123452345634567
  id: 2
  time: "07:20"
  temp: 21
  days: "yyyyyyy"
  climatisation: true
````
